---

- name: Add k8s user
  user: name="k8s" password="{{user_password}}" home="/home/k8s" shell="/bin/bash" update_password="on_create" groups="sudo"

- name: Add authorized_keys for k8s user
  authorized_key: user=k8s key="{{ lookup('file', '/home/k8s/.ssh/id_rsa.pub') }}"

- name: ensure private key and public one are present
  copy: 
    src: "/home/k8s/.ssh"
    dest: "/home/k8s/.ssh/{{ item }}" 
    mode: 0400
  with_items:
    - id_dsa.pub
    - id_dsa

- name: Ensure wheel group can sudo without password
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='k8s ALL=(root) NOPASSWD: ALL'"

